In [1]:
import numpy as np
import pandas as pd

# Numpy

## 1. Write a Python program using NumPy to create a 1D, and 2D array and display their dimensions and shapes.

In [2]:
oneD_array = np.array([12,35,45,89,65])

twoD_array = np.array([[15,30],[20,8],
                       [6,24],[56,85]])

print("Shape of 1D array",oneD_array.shape)
print("Shape of 2D array",twoD_array.shape)

print("Dimension of array",np.ndim(oneD_array))
print("Dimension of array",np.ndim(twoD_array))

Shape of 1D array (5,)
Shape of 2D array (4, 2)
Dimension of array 1
Dimension of array 2


## 2. Create a NumPy array of 10 random integers between 1 and 100, and find the maximum, minimum, mean, and standard deviation.

In [3]:
import numpy as np 
random_num = np.random.randint(1,100, size = 10)

print(random_num)

print("Maximum number is",np.max(random_num))
print("Minimum number is",np.min(random_num))
print("Mean of random number is",np.mean(random_num))
print("Standard deviation of random number is",np.std(random_num))

[ 7 42 72 59 41 71 22 81 91 82]
Maximum number is 91
Minimum number is 7
Mean of random number is 56.8
Standard deviation of random number is 26.434068926292827


## 3. Write a program to demonstrate slicing and indexing on a NumPy array.

In [4]:
arr1 = np.array([15,65,8,45,75,95,35,22,11,20])

print("\n--- 1D Array Indexing ---")
print("Element at index 3:", arr1[3])
print("Element at last index", arr1[-1])

print("\n--- 1D Array Slicing ---")
print("Slice from index 2 to 5", arr1[2:6])
print("Slice from beginning to index 4:", arr1[:5])
print("Slice from index 7 to end:", arr1[7:])
print("Slice with a step of 2:", arr1[0:10:2])
print("Reverse the array using slicing:", arr1[::-1])


arr2 = np.array([[10, 11, 12, 13],
                   [14, 15, 16, 17],
                   [18, 19, 20, 21]])

# --- Indexing on 2D arrays ---
print("\n--- 2D Array Indexing ---")
print("Element at row 0, column 1:", arr2[0, 1])
print("Element at row 2, column 3:", arr2[2, 3])

# --- Slicing on 2D arrays ---
print("\n--- 2D Array Slicing ---")
print("First row:", arr2[0, :])
print("Second column:", arr2[:, 1])
print("rows 1-2, columns 0-2:\n", arr2[1:3, 0:3])


--- 1D Array Indexing ---
Element at index 3: 45
Element at last index 20

--- 1D Array Slicing ---
Slice from index 2 to 5 [ 8 45 75 95]
Slice from beginning to index 4: [15 65  8 45 75]
Slice from index 7 to end: [22 11 20]
Slice with a step of 2: [15  8 75 35 11]
Reverse the array using slicing: [20 11 22 35 95 75 45  8 65 15]

--- 2D Array Indexing ---
Element at row 0, column 1: 11
Element at row 2, column 3: 21

--- 2D Array Slicing ---
First row: [10 11 12 13]
Second column: [11 15 19]
rows 1-2, columns 0-2:
 [[14 15 16]
 [18 19 20]]


## 4. Create a 5×5 random matrix and compute the sum, mean, median, variance, and standard deviation along both rows and columns.

In [5]:
matrix = np.random.randint(1, 101, size=(5, 5))

print("Random 5×5 Matrix:\n", matrix)

sum_rows = np.sum(matrix, axis=1)
sum_cols = np.sum(matrix, axis=0)

mean_rows = np.mean(matrix, axis=1)
mean_cols = np.mean(matrix, axis=0)

median_rows = np.median(matrix, axis=1)
median_cols = np.median(matrix, axis=0)

var_rows = np.var(matrix, axis=1)
var_cols = np.var(matrix, axis=0)

std_rows = np.std(matrix, axis=1)
std_cols = np.std(matrix, axis=0)


print("\nSum along rows:", sum_rows)
print("Sum along columns:", sum_cols)

print("\nMean along rows:", mean_rows)
print("Mean along columns:", mean_cols)

print("\nMedian along rows:", median_rows)
print("Median along columns:", median_cols)

print("\nVariance along rows:", var_rows)
print("Variance along columns:", var_cols)

print("\nStandard Deviation along rows:", std_rows)
print("Standard Deviation along columns:", std_cols)


Random 5×5 Matrix:
 [[ 45  56  60  91  77]
 [ 71  22  86  48  89]
 [ 35  47  85  21 100]
 [ 20  74  79  93  41]
 [ 46  54  98  89  39]]

Sum along rows: [329 316 288 307 326]
Sum along columns: [217 253 408 342 346]

Mean along rows: [65.8 63.2 57.6 61.4 65.2]
Mean along columns: [43.4 50.6 81.6 68.4 69.2]

Median along rows: [60. 71. 47. 74. 54.]
Median along columns: [45. 54. 85. 89. 77.]

Variance along rows: [264.56 634.96 902.24 719.44 564.56]
Variance along columns: [277.84 283.84 154.64 840.64 621.76]

Standard Deviation along rows: [16.26530049 25.19841265 30.03731013 26.82237872 23.76047138]
Standard Deviation along columns: [16.66853323 16.84755175 12.43543325 28.99379244 24.9351158 ]


# Pandas

## 1. Create a Python program to create data frame using dictionary which contains columns like, ID, Name, Age, &amp; Salary of 15 employees. Perform all statistical operation/methods on to it.

In [6]:
df = pd.DataFrame({
    'ID' : range(1,16),
    'Name' : ['Om','Varun','Anirudhra','Tushar','Ruthwik','Shubham','Neel','Jay','Sanket','Siddhesh','Sunil','bharat','Raja','Bawa','Rahul'],
    'Age' : np.random.randint(21,50, size = 15),
    'Salary' : np.random.randint(25000,65000, size = 15)
})

df

ID       Name  Age  Salary
0    1         Om   32   35489
1    2      Varun   27   52390
2    3  Anirudhra   46   60670
3    4     Tushar   49   30279
4    5    Ruthwik   23   26776
5    6    Shubham   21   46107
6    7       Neel   26   62439
7    8        Jay   26   46258
8    9     Sanket   47   38657
9   10   Siddhesh   23   30523
10  11      Sunil   21   61242
11  12     bharat   40   55085
12  13       Raja   37   63854
13  14       Bawa   46   40168
14  15      Rahul   47   53198

In [7]:
print(df.describe())
print("--------------------")
print()

print("Mean Values:")
print("Mean",df[['Age', 'Salary']].mean())
print()

print("Median Values:")
print(df[['Age', 'Salary']].median())
print()


print("Mode Values:")
print(df[['Age', 'Salary']].mode().iloc[0])
print()

print("Variance:")
print(df[['Age', 'Salary']].var())
print()

print("Standard Deviation:")
print(df[['Age', 'Salary']].std())
print()

print("Sum:")
print(df[['Age', 'Salary']].sum())
print()

print("Minimum Values:")
print(df[['Age', 'Salary']].min())
print()

print("Maximum Values:")
print(df[['Age', 'Salary']].max())

              ID        Age        Salary
count  15.000000  15.000000     15.000000
mean    8.000000  34.066667  46875.666667
std     4.472136  10.878988  12691.258807
min     1.000000  21.000000  26776.000000
25%     4.500000  24.500000  37073.000000
50%     8.000000  32.000000  46258.000000
75%    11.500000  46.000000  57877.500000
max    15.000000  49.000000  63854.000000
--------------------

Mean Values:
Mean Age          34.066667
Salary    46875.666667
dtype: float64

Median Values:
Age          32.0
Salary    46258.0
dtype: float64

Mode Values:
Age          21.0
Salary    26776.0
Name: 0, dtype: float64

Variance:
Age       1.183524e+02
Salary    1.610681e+08
dtype: float64

Standard Deviation:
Age          10.878988
Salary    12691.258807
dtype: float64

Sum:
Age          511
Salary    703135
dtype: int64

Minimum Values:
Age          21
Salary    26776
dtype: int32

Maximum Values:
Age          49
Salary    63854
dtype: int32


## 2. Create a Python program to demonstrate how we can perform indexing and slicing operation on Student.csv file.

In [8]:
df1 = pd.DataFrame({
    "StudentID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ['Om','Varun','Anirudhra','Tushar','Ruthwik','Shubham','Neel','Sanket'],
    "Class": ['A', 'A', 'B', 'B', 'C', 'C', 'A', 'B'],
    "Marks": [85, 72, 90, 60, 88, 76, 95, 68],
    "Age": [20, 21, 19, 22, 20, 21, 23, 20]
})

df1

StudentID       Name Class  Marks  Age
0        101         Om     A     85   20
1        102      Varun     A     72   21
2        103  Anirudhra     B     90   19
3        104     Tushar     B     60   22
4        105    Ruthwik     C     88   20
5        106    Shubham     C     76   21
6        107       Neel     A     95   23
7        108     Sanket     B     68   20

In [9]:
print("\n1. Select 'Name' column:\n",df1["Name"])

print("\n2. Select 'Name' and 'Marks' columns:\n",df1[["Name", "Marks"]])

print("\n3. Access row with StudentID = 101 :\n",df1.loc[df1["StudentID"] == 101])

print("\n4. Access index 2 :\n",df1.iloc[2])

print("\n5. First 5 rows:\n",df1[:5])

print("\n6. Rows from index 2 to 6:\n",df1[2:7])

print("\n7. Slice rows (1–4) and columns (0–2):\n",df1.iloc[1:5, 0:3])

print("\n8. Students with Marks > 80:\n",df1[df1["Marks"] > 80])

print("\n9. Select columns 'Name' to 'Marks' for rows 0–4:\n",df1.loc[0:4, "Name":"Marks"])



1. Select 'Name' column:
 0           Om
1        Varun
2    Anirudhra
3       Tushar
4      Ruthwik
5      Shubham
6         Neel
7       Sanket
Name: Name, dtype: object

2. Select 'Name' and 'Marks' columns:
         Name  Marks
0         Om     85
1      Varun     72
2  Anirudhra     90
3     Tushar     60
4    Ruthwik     88
5    Shubham     76
6       Neel     95
7     Sanket     68

3. Access row with StudentID = 101 :
    StudentID Name Class  Marks  Age
0        101   Om     A     85   20

4. Access index 2 :
 StudentID          103
Name         Anirudhra
Class                B
Marks               90
Age                 19
Name: 2, dtype: object

5. First 5 rows:
    StudentID       Name Class  Marks  Age
0        101         Om     A     85   20
1        102      Varun     A     72   21
2        103  Anirudhra     B     90   19
3        104     Tushar     B     60   22
4        105    Ruthwik     C     88   20

6. Rows from index 2 to 6:
    StudentID       Name Class  Marks

## 3. Create Python program to load the Item.csv file in DataFrame, find the missing values from it. Display which column contains missing values.  Replace the missing values as follows: (The Item.csv file is uploaded in Classroom)
### Replace missing value of Quantity by median
### Replace missing value of Price by Mean
### Replace missing value of bought column by Standard Deviation
### Replace missing value of Forenoon column with maximum value
### Replace missing value of Afternoon column with minimum value
### Display all data after replacement back to user.

In [10]:
df2 = pd.read_csv('Items.csv')
df2.head()

ItemID  Quantity  Price  bought  Forenoon  Afternoon
0       1       5.0   10.5     1.0       8.0        NaN
1       2       NaN   12.0     0.0       9.0       10.0
2       3       7.0    NaN     1.0       NaN       12.0
3       4       2.0   15.0     NaN      10.0       11.0
4       5       NaN    9.5     1.0       NaN       10.0

In [11]:
df2.isnull().sum()

ItemID       0
Quantity     4
Price        3
bought       3
Forenoon     4
Afternoon    3
dtype: int64

In [12]:
# Replace missing value of Quantity by median

df2['Quantity'].fillna(df2['Quantity'].median())

0    5.0
1    4.5
2    7.0
3    2.0
4    4.5
5    4.5
6    4.0
7    4.5
8    9.0
9    3.0
Name: Quantity, dtype: float64

In [13]:
# Replace missing value of Price by Mean

df2['Price'].fillna(df2['Price'].mean())

0    10.500000
1    12.000000
2    12.285714
3    15.000000
4     9.500000
5    12.285714
6    20.000000
7     8.000000
8    12.285714
9    11.000000
Name: Price, dtype: float64

In [14]:
# Replace missing value of bought column by Standard Deviation

df2['bought'].fillna(df2['bought'].std())


0    1.000000
1    0.000000
2    1.000000
3    0.534522
4    1.000000
5    0.000000
6    0.534522
7    1.000000
8    0.000000
9    0.534522
Name: bought, dtype: float64

In [15]:
# Replace missing value of Forenoon column with maximum value

df2['Forenoon'].fillna(df2['Forenoon'].max())

0     8.0
1     9.0
2    11.0
3    10.0
4    11.0
5    11.0
6    11.0
7    11.0
8     9.0
9    10.0
Name: Forenoon, dtype: float64

In [16]:
# Replace missing value of Afternoon column with minimum value¶

df2['Afternoon'].fillna(df2['Afternoon'].min())

0    10.0
1    10.0
2    12.0
3    11.0
4    10.0
5    10.0
6    10.0
7    10.0
8    13.0
9    10.0
Name: Afternoon, dtype: float64

## 4. Create a Python program to load the Data.csv file in DataFrame, find the missing values from it. Display which column contains missing values. 
### Replace missing value as follows and display result: (The Data.csv file is uploaded in classroom)
### Replace missing value with some scalar / fix value.
### Replace missing value with value of previous row value
### Replace missing value with value of next row value.
### Replace missing value with value of previous column value
### Replace missing value with value of next row value.

In [17]:
data = pd.DataFrame({
    'A': [10, 20, np.nan, 40, 50],
    'B': [5, np.nan, 15, np.nan, 25],
    'C': [np.nan, 12, 18, np.nan, 22],
    'D': [2, 4, np.nan, 8, 10]
})

In [18]:
# Replace missing value with some scalar / fix value.
data1 = data.fillna(10)
data1

A     B     C     D
0  10.0   5.0  10.0   2.0
1  20.0  10.0  12.0   4.0
2  10.0  15.0  18.0  10.0
3  40.0  10.0  10.0   8.0
4  50.0  25.0  22.0  10.0

In [19]:
data

A     B     C     D
0  10.0   5.0   NaN   2.0
1  20.0   NaN  12.0   4.0
2   NaN  15.0  18.0   NaN
3  40.0   NaN   NaN   8.0
4  50.0  25.0  22.0  10.0

In [20]:
data

A     B     C     D
0  10.0   5.0   NaN   2.0
1  20.0   NaN  12.0   4.0
2   NaN  15.0  18.0   NaN
3  40.0   NaN   NaN   8.0
4  50.0  25.0  22.0  10.0

In [21]:
# Replace missing value with value of previous row value
data2 = data.fillna(method = "ffill")
data2

C:\Users\Om\AppData\Local\Temp\ipykernel_5032\1286866366.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2 = data.fillna(method = "ffill")


A     B     C     D
0  10.0   5.0   NaN   2.0
1  20.0   5.0  12.0   4.0
2  20.0  15.0  18.0   4.0
3  40.0  15.0  18.0   8.0
4  50.0  25.0  22.0  10.0

In [22]:
# Replace missing value with value of next row value.
data3 = data.fillna(method = "bfill")
data3

C:\Users\Om\AppData\Local\Temp\ipykernel_5032\3990096947.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data3 = data.fillna(method = "bfill")


A     B     C     D
0  10.0   5.0  12.0   2.0
1  20.0  15.0  12.0   4.0
2  40.0  15.0  18.0   8.0
3  40.0  25.0  22.0   8.0
4  50.0  25.0  22.0  10.0

In [25]:
data

A     B     C     D
0  10.0   5.0   NaN   2.0
1  20.0   NaN  12.0   4.0
2   NaN  15.0  18.0   NaN
3  40.0   NaN   NaN   8.0
4  50.0  25.0  22.0  10.0

In [23]:
# Replace missing value with value of previous column value
data4 = data.fillna(method = "ffill" ,axis=1)
data4

C:\Users\Om\AppData\Local\Temp\ipykernel_5032\1079128399.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data4 = data.fillna(method = "ffill" ,axis=1)


A     B     C     D
0  10.0   5.0   5.0   2.0
1  20.0  20.0  12.0   4.0
2   NaN  15.0  18.0  18.0
3  40.0  40.0  40.0   8.0
4  50.0  25.0  22.0  10.0

In [24]:
# Replace missing value with value of next row value.
data5 = data.fillna(method = "bfill", axis = 1)
data5

C:\Users\Om\AppData\Local\Temp\ipykernel_5032\1960521366.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data5 = data.fillna(method = "bfill", axis = 1)


A     B     C     D
0  10.0   5.0   2.0   2.0
1  20.0  12.0  12.0   4.0
2  15.0  15.0  18.0   NaN
3  40.0   8.0   8.0   8.0
4  50.0  25.0  22.0  10.0